import sys
import time
from datetime import datetime
from io import BytesIO
from pathlib import Path
from typing import Any

import pandas as pd
import pydeck as pdk
import streamlit as st
from dotenv import load_dotenv
from geopy.geocoders import Nominatim
from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.enrichment.website_enricher import enrich_leads
from src.lead_sources.serpapi_maps import save_leads_to_csv, search_google_maps
from src.outreach.contactability import evaluate_contactability_batch
from src.outreach.email_generator import generate_outreach_batch
from src.scoring.lead_scorer import score_leads

load_dotenv()

geolocator = Nominatim(user_agent="ai_lead_generation_agents")


def _safe_filename(value: str) -> str:
    cleaned = "".join(ch if ch.isalnum() or ch in {"-", "_"} else "_" for ch in value.lower())
    cleaned = "_".join(part for part in cleaned.split("_") if part)
    return cleaned[:80] or "lead_report"


def build_growth_report_pdf(lead: dict) -> bytes:
    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=LETTER,
        leftMargin=0.7 * inch,
        rightMargin=0.7 * inch,
        topMargin=0.7 * inch,
        bottomMargin=0.7 * inch,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "ReportTitle",
        parent=styles["Title"],
        fontSize=20,
        leading=24,
        textColor=colors.HexColor("#0f172a"),
        spaceAfter=10,
        alignment=TA_LEFT,
    )
    subtitle_style = ParagraphStyle(
        "ReportSubtitle",
        parent=styles["Normal"],
        fontSize=9.5,
        leading=12,
        textColor=colors.HexColor("#475569"),
        spaceAfter=12,
    )
    section_style = ParagraphStyle(
        "SectionHeader",
        parent=styles["Heading2"],
        fontSize=11.5,
        leading=14,
        textColor=colors.white,
        backColor=colors.HexColor("#0f172a"),
        spaceBefore=8,
        spaceAfter=6,
        leftIndent=6,
    )
    body_style = ParagraphStyle(
        "BodyTextCustom",
        parent=styles["BodyText"],
        fontSize=10.5,
        leading=14,
        textColor=colors.HexColor("#111827"),
        spaceAfter=8,
    )
    small_style = ParagraphStyle(
        "SmallText",
        parent=styles["BodyText"],
        fontSize=9,
        leading=12,
        textColor=colors.HexColor("#64748b"),
    )

    name = str(lead.get("name") or "Unknown Business")
    website = str(lead.get("website") or "Not available")
    score = str(lead.get("score") or "N/A")
    status = str(lead.get("contactability_status") or "unknown")
    tech_stack = str(lead.get("tech_stack") or "Not detected")
    feature_summary = str(lead.get("feature_summary") or "Not available")
    seo_summary = str(lead.get("seo_summary") or "Not available")
    opportunity = str(lead.get("opportunity") or "No opportunity identified.")
    reasoning = str(lead.get("reasoning") or "No additional reasoning available.")
    generated_on = datetime.now().strftime("%B %d, %Y")

    story = []
    story.append(Paragraph("AI Website Growth Report", title_style))
    story.append(
        Paragraph(
            f"Generated by AI Lead Generation Agents | {generated_on}",
            subtitle_style,
        )
    )

    summary_table = Table(
        [
            ["Business", name],
            ["Website", website],
            ["Lead Score", f"{score} / 10"],
            ["Status", status],
            ["Tech Stack", tech_stack],
        ],
        colWidths=[1.4 * inch, 4.8 * inch],
    )
    summary_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#e2e8f0")),
                ("TEXTCOLOR", (0, 0), (-1, -1), colors.HexColor("#111827")),
                ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 9.5),
                ("LEADING", (0, 0), (-1, -1), 12),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#cbd5e1")),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ("TOPPADDING", (0, 0), (-1, -1), 7),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
            ]
        )
    )
    story.append(summary_table)
    story.append(Spacer(1, 12))

    story.append(Paragraph("Conversion Signals", section_style))
    story.append(Paragraph(feature_summary, body_style))
    story.append(Paragraph("SEO Signals", section_style))
    story.append(Paragraph(seo_summary, body_style))
    story.append(Paragraph("Opportunity", section_style))
    story.append(Paragraph(opportunity, body_style))
    story.append(Paragraph("AI Reasoning", section_style))
    story.append(Paragraph(reasoning, body_style))

    growth_report = str(lead.get("growth_report") or "").strip()
    if growth_report:
        story.append(Paragraph("Full Report", section_style))
        for block in [line.strip() for line in growth_report.split("\n") if line.strip()]:
            story.append(Paragraph(block, body_style))

    story.append(Spacer(1, 8))
    story.append(
        Paragraph(
            "Prepared as a quick outreach audit based on visible homepage signals and AI lead analysis.",
            small_style,
        )
    )

    doc.build(story)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes


@st.cache_data(show_spinner=False)
def geocode_address_with_fallback(address: str, city: str = "", state: str = "FL"):
    if not address or not str(address).strip():
        return None, None, "missing"

    raw_address = str(address).strip()
    candidates = [raw_address]

    simplified = raw_address
    for token in ["STE", "SUITE", "UNIT", "#"]:
        if token in simplified.upper():
            upper = simplified.upper()
            idx = upper.find(token)
            if idx != -1:
                simplified = simplified[:idx].strip().rstrip(",")
                break
    if simplified and simplified != raw_address:
        candidates.append(simplified)

    if city:
        candidates.append(f"{city}, {state}")

    for i, candidate in enumerate(candidates[:2]):
        try:
            location = geolocator.geocode(candidate, timeout=2)
            if location:
                if i == 0:
                    return location.latitude, location.longitude, "exact"
                if i == 1:
                    return location.latitude, location.longitude, "simplified"
                return location.latitude, location.longitude, "city_fallback"
        except Exception:
            continue

    return None, None, "failed"

@st.cache_data(show_spinner=False)
def get_city_center(city: str, state: str = "FL"):
    if not city or not str(city).strip():
        return None, None

    try:
        location = geolocator.geocode(f"{city}, {state}", timeout=10)
        if location:
            return location.latitude, location.longitude
    except Exception:
        pass

    return None, None


def parse_sidebar_inputs(niches_input: str, cities_input: str):
    niches = [line.strip() for line in niches_input.splitlines() if line.strip()]
    cities = [line.strip() for line in cities_input.splitlines() if line.strip()]

    if not niches:
        raise ValueError("Please enter at least one niche.")
    if not cities:
        raise ValueError("Please enter at least one city.")

    search_pairs = [(niche, city) for niche in niches for city in cities]
    return niches, cities, search_pairs


def _lead_identity(lead: dict) -> str:
    place_id = str(lead.get("place_id") or "").strip()
    if place_id:
        return f"place:{place_id}"

    name = str(lead.get("name") or "").strip().lower()
    address = str(lead.get("address") or "").strip().lower()
    city = str(lead.get("search_city") or "").strip().lower()
    return f"name_addr_city:{name}|{address}|{city}"


def _dedupe_discovered_leads(raw_leads_all: list[dict]) -> list[dict]:
    deduped = []
    seen_keys = set()

    for lead in raw_leads_all:
        dedupe_key = _lead_identity(lead)
        if dedupe_key in seen_keys:
            continue
        seen_keys.add(dedupe_key)
        deduped.append(lead)

    return deduped


def _build_filtered_views(ready_leads: list[dict], min_score: int):
    df = pd.DataFrame(ready_leads)
    if df.empty:
        return df, df.copy(), df.copy()

    if "score" in df.columns:
        df["score_numeric"] = pd.to_numeric(df["score"], errors="coerce")
        filtered_df = df[df["score_numeric"] >= min_score].copy()
        filtered_df = filtered_df.sort_values(by="score_numeric", ascending=False)
    else:
        filtered_df = df.copy()

    if "email" not in filtered_df.columns:
        filtered_df["email"] = ""

    outreach_df = filtered_df[
        filtered_df["email"].fillna("").astype(str).str.strip() != ""
    ].copy()
    other_scored_df = filtered_df[
        filtered_df["email"].fillna("").astype(str).str.strip() == ""
    ].copy()

    return filtered_df, outreach_df, other_scored_df


def execute_full_pipeline(
    niches: list[str],
    cities: list[str],
    max_results: int,
    outreach_limit: int,
    min_score: int,
    progress_bar,
    status_text,
):
    data_dir = PROJECT_ROOT / "data"
    data_dir.mkdir(exist_ok=True)

    raw_path = data_dir / "leads_raw.csv"
    enriched_path = data_dir / "leads_enriched.csv"
    scored_path = data_dir / "leads_scored.csv"
    outreach_path = data_dir / "leads_outreach.csv"
    ready_path = data_dir / "leads_ready.csv"

    search_pairs = [(niche, city) for niche in niches for city in cities]
    timings = {}

    status_text.info("Step 1/5: Discovering leads across niches and cities...")
    t0 = time.perf_counter()
    raw_leads_all = []

    for niche_value, city_value in search_pairs:
        combo_query = f"{niche_value} in {city_value}"
        combo_results = search_google_maps(
            query=combo_query,
            max_results=int(max_results),
        )
        for lead in combo_results:
            enriched_lead = dict(lead)
            enriched_lead["search_niche"] = niche_value
            enriched_lead["search_city"] = city_value
            enriched_lead["search_query"] = combo_query
            raw_leads_all.append(enriched_lead)

    raw_leads = _dedupe_discovered_leads(raw_leads_all)
    save_leads_to_csv(raw_leads, str(raw_path))
    timings["Lead Discovery"] = time.perf_counter() - t0
    progress_bar.progress(20)

    status_text.info("Step 2/5: Enriching websites...")
    t0 = time.perf_counter()
    enriched_leads = enrich_leads(
        raw_leads,
        limit=len(raw_leads),
        sleep_seconds=0.0,
        max_workers=6,
    )
    pd.DataFrame(enriched_leads).to_csv(enriched_path, index=False)
    timings["Website Enrichment"] = time.perf_counter() - t0
    progress_bar.progress(40)

    status_text.info("Step 3/5: Scoring leads with AI...")
    t0 = time.perf_counter()
    scored_leads = score_leads(
        enriched_leads,
        limit=len(enriched_leads),
        sleep_seconds=0.0,
        max_workers=6,
    )
    pd.DataFrame(scored_leads).to_csv(scored_path, index=False)
    timings["AI Scoring"] = time.perf_counter() - t0
    progress_bar.progress(60)

    status_text.info("Step 4/5: Generating outreach...")
    t0 = time.perf_counter()
    scored_sorted = sorted(
        scored_leads,
        key=lambda row: pd.to_numeric(row.get("score"), errors="coerce")
        if pd.notna(pd.to_numeric(row.get("score"), errors="coerce"))
        else -1,
        reverse=True,
    )
    top_for_outreach = scored_sorted[: int(outreach_limit)]

    outreach_subset = generate_outreach_batch(
        top_for_outreach,
        limit=len(top_for_outreach),
        sleep_seconds=0.0,
        max_workers=6,
    )

    outreach_by_key = {_lead_identity(lead): lead for lead in outreach_subset}
    merged_leads = []
    for lead in scored_leads:
        key = _lead_identity(lead)
        if key in outreach_by_key:
            merged_leads.append(outreach_by_key[key])
        else:
            base = dict(lead)
            base.update(
                {
                    "subject": "",
                    "email": "",
                    "cta": "",
                    "followup_1": "",
                    "followup_2": "",
                    "outreach_error": None,
                }
            )
            merged_leads.append(base)

    pd.DataFrame(merged_leads).to_csv(outreach_path, index=False)
    timings["Outreach Generation"] = time.perf_counter() - t0
    progress_bar.progress(80)

    status_text.info("Step 5/5: Running contactability review...")
    t0 = time.perf_counter()
    ready_leads = evaluate_contactability_batch(merged_leads)
    pd.DataFrame(ready_leads).to_csv(ready_path, index=False)
    timings["Contactability Review"] = time.perf_counter() - t0
    progress_bar.progress(100)

    ready_count = sum(1 for row in ready_leads if row.get("contactability_status") == "ready")
    review_count = sum(
        1 for row in ready_leads if row.get("contactability_status") == "review"
    )

    filtered_df, outreach_df, other_scored_df = _build_filtered_views(
        ready_leads=ready_leads,
        min_score=int(min_score),
    )
    map_df = filtered_df.copy()

    return {
        "raw_leads": raw_leads,
        "enriched_leads": enriched_leads,
        "scored_leads": scored_leads,
        "ready_leads": ready_leads,
        "filtered_df": filtered_df,
        "map_df": map_df,
        "outreach_df": outreach_df,
        "other_scored_df": other_scored_df,
        "outreach_subset": outreach_subset,
        "ready_count": ready_count,
        "review_count": review_count,
        "timings": timings,
        "search_pairs": search_pairs,
        "niches": niches,
        "cities": cities,
        "status_message": (
            f"Pipeline complete for {len(search_pairs)} search combination(s) "
            f"across {len(niches)} niche(s) and {len(cities)} city(s)."
        ),
        "output_paths": {
            "raw": str(raw_path),
            "enriched": str(enriched_path),
            "scored": str(scored_path),
            "outreach": str(outreach_path),
            "ready": str(ready_path),
        },
        "run_settings": {
            "max_results": int(max_results),
            "outreach_limit": int(outreach_limit),
            "min_score": int(min_score),
        },
    }


def _ensure_dataframe(value):
    if isinstance(value, pd.DataFrame):
        return value.copy()
    if value is None:
        return pd.DataFrame()
    return pd.DataFrame(value)


def prepare_map_dataframe(filtered_df: pd.DataFrame) -> pd.DataFrame:
    map_df = _ensure_dataframe(filtered_df)

    if "search_city" not in map_df.columns:
        map_df["search_city"] = ""
    if "latitude" not in map_df.columns:
        map_df["latitude"] = None
    if "longitude" not in map_df.columns:
        map_df["longitude"] = None
    if "geocode_quality" not in map_df.columns:
        map_df["geocode_quality"] = None

    if map_df.empty:
        return map_df

    # ORIGINAL GEOCODING LOOP (the version that worked before)
    missing_coords_mask = map_df["latitude"].isna() | map_df["longitude"].isna()

    for idx, row in map_df.loc[missing_coords_mask].iterrows():
        lat, lon, quality = geocode_address_with_fallback(
            row.get("address", ""),
            city=row.get("search_city", ""),
            state="FL",
        )

        map_df.at[idx, "latitude"] = lat
        map_df.at[idx, "longitude"] = lon
        map_df.at[idx, "geocode_quality"] = quality

    quality_empty_mask = map_df["geocode_quality"].isna() | (
        map_df["geocode_quality"].astype(str).str.strip() == ""
    )

    provided_coords_mask = map_df["latitude"].notna() & map_df["longitude"].notna()

    map_df.loc[quality_empty_mask & provided_coords_mask, "geocode_quality"] = "provided"

    return map_df


def _score_badge_color(score) -> str:
    numeric_score = pd.to_numeric(score, errors="coerce")
    if pd.notna(numeric_score) and numeric_score >= 7:
        return "#22c55e"
    if pd.notna(numeric_score) and numeric_score >= 5:
        return "#3b82f6"
    return "#f59e0b"


def _status_badge_color(status: str) -> str:
    return "#16a34a" if str(status).lower() == "ready" else "#f59e0b"


def _render_map_section(prepared_map_df: pd.DataFrame):
    st.markdown("---")
    st.subheader("Lead Map")

    available_map_cities = sorted(
        {
            str(value).strip()
            for value in prepared_map_df.get("search_city", pd.Series(dtype=str)).dropna().tolist()
            if str(value).strip()
        }
    )
    map_options = ["All Cities"] + available_map_cities

    if st.session_state.get("map_city_selection") not in map_options:
        st.session_state.map_city_selection = "All Cities"

    st.selectbox(
        "Jump to city",
        options=map_options,
        key="map_city_selection",
    )
    map_city_selection = st.session_state.map_city_selection

    if available_map_cities:
        st.caption("Available cities on map: " + ", ".join(available_map_cities))

    # Start from persisted map rows, then geocode missing coordinates on demand.
    map_df = prepared_map_df.copy()
    if map_city_selection != "All Cities" and "search_city" in map_df.columns:
        map_df = map_df[
            map_df["search_city"].fillna("").astype(str).str.strip() == map_city_selection
        ].copy()

    if "search_city" not in map_df.columns:
        map_df["search_city"] = ""
    if "latitude" not in map_df.columns:
        map_df["latitude"] = None
    if "longitude" not in map_df.columns:
        map_df["longitude"] = None
    if "geocode_quality" not in map_df.columns:
        map_df["geocode_quality"] = None

    # Keep geocoding in map render path (previous working behavior).
    missing_coords_mask = map_df["latitude"].isna() | map_df["longitude"].isna()

    for idx, row in map_df.loc[missing_coords_mask].head(10).iterrows():
        lat, lon, quality = geocode_address_with_fallback(
            row.get("address", ""),
            city=row.get("search_city", ""),
            state="FL",
        )
        map_df.at[idx, "latitude"] = lat
        map_df.at[idx, "longitude"] = lon
        map_df.at[idx, "geocode_quality"] = quality

        plotted_df = map_df.dropna(subset=["latitude", "longitude"]).copy()

    if plotted_df.empty:
        st.info(
            f"Map coordinates could not be generated for the current filtered leads"
            + (f" in {map_city_selection}." if map_city_selection != "All Cities" else ".")
        )
        return

    plotted_df["tooltip_name"] = plotted_df["name"].fillna("Unknown Lead")
    plotted_df["tooltip_score"] = plotted_df["score"].fillna("N/A")
    plotted_df["tooltip_status"] = plotted_df["contactability_status"].fillna("unknown")
    plotted_df["tooltip_address"] = plotted_df["address"].fillna("")
    plotted_df["tooltip_geocode_quality"] = plotted_df["geocode_quality"].fillna("unknown")

    def marker_color(row):
        score = pd.to_numeric(row.get("score"), errors="coerce")
        status = str(row.get("contactability_status", "")).lower()

        if status == "review":
            return [245, 158, 11, 220]
        if pd.notna(score) and score >= 7:
            return [34, 197, 94, 220]
        if pd.notna(score) and score >= 5:
            return [59, 130, 246, 220]
        return [156, 163, 175, 220]

    plotted_df["marker_color"] = plotted_df.apply(marker_color, axis=1)

    coord_counts = {}
    adjusted_lats = []
    adjusted_lons = []

    for _, row in plotted_df.iterrows():
        key = (round(float(row["latitude"]), 5), round(float(row["longitude"]), 5))
        count = coord_counts.get(key, 0)
        lat_offset = 0.00025 * count
        lon_offset = 0.00025 * count
        adjusted_lats.append(float(row["latitude"]) + lat_offset)
        adjusted_lons.append(float(row["longitude"]) + lon_offset)
        coord_counts[key] = count + 1

    plotted_df["plot_latitude"] = adjusted_lats
    plotted_df["plot_longitude"] = adjusted_lons

    center_lat = plotted_df["plot_latitude"].mean()
    center_lon = plotted_df["plot_longitude"].mean()

    layer = pdk.Layer(
        "ScatterplotLayer",
        data=plotted_df,
        get_position="[plot_longitude, plot_latitude]",
        get_radius=220,
        get_fill_color="marker_color",
        pickable=True,
    )

    view_state = pdk.ViewState(
        latitude=center_lat,
        longitude=center_lon,
        zoom=12,
        pitch=0,
    )

    tooltip = {
        "html": """
            <b>{tooltip_name}</b><br/>
            Score: {tooltip_score}<br/>
            Status: {tooltip_status}<br/>
            Geocode: {tooltip_geocode_quality}<br/>
            {tooltip_address}
        """,
        "style": {
            "backgroundColor": "rgba(15, 23, 42, 0.95)",
            "color": "white",
            "fontSize": "13px",
            "padding": "10px",
            "borderRadius": "8px",
        },
    }

    deck = pdk.Deck(
        layers=[layer],
        initial_view_state=view_state,
        tooltip=tooltip,
        map_style="dark",
    )
    st.pydeck_chart(deck, use_container_width=True)

    missing_count = len(map_df) - len(plotted_df)
    if missing_count > 0:
        st.caption(f"{missing_count} lead(s) could not be mapped because coordinates were not found.")


def render_pipeline_results(results):
    raw_leads = results.get("raw_leads", [])
    scored_leads = results.get("scored_leads", [])
    outreach_subset = results.get("outreach_subset", [])
    ready_count = results.get("ready_count", 0)
    review_count = results.get("review_count", 0)
    timings = results.get("timings", {})
    search_pairs = results.get("search_pairs", [])
    filtered_df = _ensure_dataframe(results.get("filtered_df"))
    map_df = _ensure_dataframe(results.get("map_df"))
    if map_df.empty:
        map_df = filtered_df.copy()

    st.subheader("Pipeline Results")
    m1, m2, m3, m4, m5, m6 = st.columns(6)
    m1.metric("Search Combos", len(search_pairs))
    m2.metric("Raw", len(raw_leads))
    m3.metric("Scored", len(scored_leads))
    m4.metric("Outreach Generated", f"{len(outreach_subset)} / {len(scored_leads)}")
    m5.metric("Ready", ready_count)
    m6.metric("Review", review_count)

    st.markdown("---")
    st.subheader("Stage Timings")
    timing_df = pd.DataFrame(
        [{"Stage": stage, "Seconds": round(seconds, 2)} for stage, seconds in timings.items()]
    )
    st.dataframe(timing_df, use_container_width=True, hide_index=True)

    _render_map_section(map_df)


def _render_export_controls(filtered_df: pd.DataFrame, export_mode: str):
    if export_mode == "Outreach Ready":
        export_columns = [
            "search_niche",
            "search_city",
            "search_query",
            "name",
            "website",
            "score",
            "opportunity",
            "feature_summary",
            "missing_features",
            "seo_summary",
            "has_meta_description",
            "best_contact_email",
            "contact_email_quality",
            "contact_email_score",
            "contact_page_url",
            "subject",
            "email",
            "contactability_status",
        ]
        export_df = filtered_df[[c for c in export_columns if c in filtered_df.columns]].copy()
        export_filename = "outreach_ready.csv"

    elif export_mode == "Lead List Only":
        export_columns = [
            "search_niche",
            "search_city",
            "search_query",
            "name",
            "address",
            "phone",
            "website",
            "rating",
            "reviews",
            "score",
            "feature_summary",
            "missing_features",
            "seo_summary",
            "has_meta_description",
            "best_contact_email",
            "contact_email_quality",
            "contact_email_score",
            "contact_page_url",
            "contactability_status",
        ]
        export_df = filtered_df[[c for c in export_columns if c in filtered_df.columns]].copy()
        export_filename = "lead_list_only.csv"

    else:  # CRM Upload
        export_df = filtered_df.copy().rename(columns={"name": "company_name", "opportunity": "notes"})
        crm_columns = [
            "search_niche",
            "search_city",
            "search_query",
            "company_name",
            "website",
            "phone",
            "address",
            "score",
            "notes",
            "feature_summary",
            "missing_features",
            "seo_summary",
            "best_contact_email",
            "contact_email_quality",
            "contact_email_score",
            "contact_page_url",
        ]
        export_df = export_df[[c for c in crm_columns if c in export_df.columns]].copy()
        export_filename = "crm_upload.csv"

    csv_data = export_df.to_csv(index=False).encode("utf-8")
    st.download_button(
        label=f"Download {export_mode} CSV",
        data=csv_data,
        file_name=export_filename,
        mime="text/csv",
        use_container_width=True,
    )


def render_full_results(results, export_mode: str):
    filtered_df = _ensure_dataframe(results.get("filtered_df"))
    outreach_df = _ensure_dataframe(results.get("outreach_df"))
    other_scored_df = _ensure_dataframe(results.get("other_scored_df"))
    search_pairs = results.get("search_pairs", [])
    niches = results.get("niches", [])
    cities = results.get("cities", [])

    status_message = results.get(
        "status_message",
        (
            f"Pipeline complete for {len(search_pairs)} search combination(s) "
            f"across {len(niches)} niche(s) and {len(cities)} city(s)."
        ),
    )
    st.success(status_message)
    st.caption(
        "Running combinations: "
        + ", ".join(f"{n} in {c}" for n, c in search_pairs[:8])
        + (" ..." if len(search_pairs) > 8 else "")
    )

    render_pipeline_results(results)

    st.markdown("---")
    st.subheader(f"Top Opportunities ({len(outreach_df)})")
    st.caption(
        f"Showing the top {len(outreach_df)} leads selected for outreach generation "
        f"out of {len(filtered_df)} scored leads."
    )

    for lead in outreach_df.to_dict(orient="records"):
        name = lead.get("name", "Unknown Lead")
        score = lead.get("score", "N/A")
        status = lead.get("contactability_status", "unknown")
        opportunity = lead.get("opportunity", "No opportunity available.")
        website = lead.get("website", "")
        subject = lead.get("subject", "")
        tech_stack = lead.get("tech_stack", "")
        feature_summary = lead.get("feature_summary", "")
        seo_summary = lead.get("seo_summary", "")
        best_contact_email = lead.get("best_contact_email", "")
        contact_email_quality = lead.get("contact_email_quality", "none")
        contact_email_score = lead.get("contact_email_score", 0)

        score_color = _score_badge_color(score)
        status_color = _status_badge_color(status)

        st.markdown(
            f"""
            <div class="opportunity-card">
                <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:10px;">
                    <div style="font-size:1.1rem; font-weight:700;">{name}</div>
                    <div style="display:flex; gap:8px;">
                        <span style="
                            background:{score_color};
                            padding:6px 10px;
                            border-radius:999px;
                            font-size:0.85rem;
                            font-weight:600;
                            color:white;
                        ">Score: {score}</span>
                        <span style="
                            background:{status_color};
                            color:white;
                            padding:6px 10px;
                            border-radius:999px;
                            font-size:0.85rem;
                            font-weight:600;
                        ">{status}</span>
                    </div>
                </div>
                <div style="margin-bottom:10px;">
                    <strong>Opportunity:</strong> {opportunity}
                </div>
                <div style="margin-bottom:10px;">
                    <strong>Tech Stack:</strong> {tech_stack if tech_stack else "Not detected"}
                </div>
                <div style="margin-bottom:10px;">
                    <strong>Conversion Signals:</strong> {feature_summary if feature_summary else "Not available"}
                </div>
                <div style="margin-bottom:10px;">
                    <strong>SEO Signals:</strong> {seo_summary if seo_summary else "Not available"}
                </div>
                <div style="margin-bottom:10px;">
                    <strong>Contact Email:</strong> {best_contact_email if best_contact_email else "Not found"}
                </div>
                <div style="margin-bottom:10px;">
                    <strong>Contact Email Quality:</strong> {contact_email_quality if contact_email_quality else "none"}
                </div>
                <div style="margin-bottom:10px;">
                    <strong>Contact Email Score:</strong> {contact_email_score}
                </div>
                <div style="margin-bottom:10px;">
                    <strong>Website:</strong> <a href="{website}" target="_blank">{website}</a>
                </div>
                <div>
                    <strong>Suggested Subject:</strong> {subject}
                </div>
            </div>
            """,
            unsafe_allow_html=True,
        )

    if not other_scored_df.empty:
        st.markdown("---")
        st.subheader(f"Other Scored Leads ({len(other_scored_df)})")
        st.caption(
            "These leads were discovered and scored, but outreach was not generated due to the outreach limit."
        )

        for lead in other_scored_df.to_dict(orient="records"):
            name = lead.get("name", "Unknown Lead")
            score = lead.get("score", "N/A")
            status = lead.get("contactability_status", "unknown")
            opportunity = lead.get("opportunity", "No opportunity available.")
            website = lead.get("website", "")
            tech_stack = lead.get("tech_stack", "")
            feature_summary = lead.get("feature_summary", "")
            seo_summary = lead.get("seo_summary", "")
            best_contact_email = lead.get("best_contact_email", "")
            contact_email_quality = lead.get("contact_email_quality", "none")
            contact_email_score = lead.get("contact_email_score", 0)

            score_color = _score_badge_color(score)
            status_color = _status_badge_color(status)

            st.markdown(
                f"""
                <div class="opportunity-card">
                    <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:10px;">
                        <div style="font-size:1.1rem; font-weight:700;">{name}</div>
                        <div style="display:flex; gap:8px;">
                            <span style="
                                background:{score_color};
                                padding:6px 10px;
                                border-radius:999px;
                                font-size:0.85rem;
                                font-weight:600;
                                color:white;
                            ">Score: {score}</span>
                            <span style="
                                background:{status_color};
                                color:white;
                                padding:6px 10px;
                                border-radius:999px;
                                font-size:0.85rem;
                                font-weight:600;
                            ">{status}</span>
                        </div>
                    </div>
                    <div style="margin-bottom:10px;">
                        <strong>Opportunity:</strong> {opportunity}
                    </div>
                    <div style="margin-bottom:10px;">
                        <strong>Tech Stack:</strong> {tech_stack if tech_stack else "Not detected"}
                    </div>
                    <div style="margin-bottom:10px;">
                        <strong>Conversion Signals:</strong> {feature_summary if feature_summary else "Not available"}
                    </div>
                    <div style="margin-bottom:10px;">
                        <strong>SEO Signals:</strong> {seo_summary if seo_summary else "Not available"}
                    </div>
                    <div style="margin-bottom:10px;">
                    <strong>Contact Email:</strong> {best_contact_email if best_contact_email else "Not found"}
                    </div>
                    <div style="margin-bottom:10px;">
                        <strong>Contact Email Quality:</strong> {contact_email_quality if contact_email_quality else "none"}
                    </div>
                    <div style="margin-bottom:10px;">
                        <strong>Contact Email Score:</strong> {contact_email_score}
                    </div>
                    <div style="margin-bottom:10px;">
                        <strong>Website:</strong> <a href="{website}" target="_blank">{website}</a>
                    </div>
                    <div>
                        <strong>Outreach:</strong> Not generated (outside outreach limit)
                    </div>
                </div>
                """,
                unsafe_allow_html=True,
            )

    st.markdown("---")
    st.subheader("Lead Details")

    for lead in outreach_df.to_dict(orient="records"):
        company_name = lead.get("name", "Unknown Lead")
        score = lead.get("score", "N/A")
        status = lead.get("contactability_status", "unknown")
        subject = lead.get("subject", "")
        email = lead.get("email", "")
        followup_1 = lead.get("followup_1", "")
        followup_2 = lead.get("followup_2", "")
        lead_key = _safe_filename(_lead_identity(lead))

        with st.expander(f"{company_name} | Score: {score} | Status: {status}"):
            left, right = st.columns([1, 1])

            with left:
                st.write("**Website**")
                st.write(lead.get("website", ""))

                st.write("**Tech Stack**")
                st.write(lead.get("tech_stack", "") or "Not detected")

                st.write("**Conversion Signals**")
                st.write(lead.get("feature_summary", "") or "Not available")

                st.write("**SEO Signals**")
                st.write(lead.get("seo_summary", "") or "Not available")

                st.write("**Best Contact Email**")
                st.write(lead.get("best_contact_email", "") or "Not found")

                st.write("**Contact Email Quality**")
                st.write(lead.get("contact_email_quality", "") or "none")

                st.write("**Contact Email Score**")
                st.write(lead.get("contact_email_score", 0))

                st.write("**Contact Page URL**")
                st.write(lead.get("contact_page_url", "") or "Not found")

                st.write("**Opportunity**")
                st.write(lead.get("opportunity", ""))

                st.write("**AI Website Growth Report**")
                st.text_area(
                    label=f"report_{lead_key}",
                    value=lead.get("growth_report", ""),
                    height=220,
                    key=f"report_{lead_key}",
                    label_visibility="collapsed",
                )

                pdf_bytes = build_growth_report_pdf(lead)
                pdf_filename = f"{_safe_filename(company_name)}_growth_report.pdf"

                st.download_button(
                    label="Download Growth Report PDF",
                    data=pdf_bytes,
                    file_name=pdf_filename,
                    mime="application/pdf",
                    key=f"pdf_report_{lead_key}",
                    use_container_width=True,
                )

                st.write("**Contactability**")
                st.write(lead.get("contactability_reason", ""))

                st.write("**Suggested Subject**")
                st.text_area(
                    label=f"subject_{lead_key}",
                    value=subject,
                    height=68,
                    key=f"subject_{lead_key}",
                    label_visibility="collapsed",
                )

            with right:
                tab1, tab2, tab3 = st.tabs(["Initial Email", "Follow-up 1", "Follow-up 2"])

                with tab1:
                    st.text_area(
                        label=f"email_{lead_key}",
                        value=email,
                        height=220,
                        key=f"email_{lead_key}",
                        label_visibility="collapsed",
                    )

                with tab2:
                    st.text_area(
                        label=f"followup1_{lead_key}",
                        value=followup_1,
                        height=180,
                        key=f"followup1_{lead_key}",
                        label_visibility="collapsed",
                    )

                with tab3:
                    st.text_area(
                        label=f"followup2_{lead_key}",
                        value=followup_2,
                        height=180,
                        key=f"followup2_{lead_key}",
                        label_visibility="collapsed",
                    )

        st.markdown("---")

    _render_export_controls(filtered_df, export_mode)


st.set_page_config(page_title="AI Lead Generation Agents", layout="wide")
if "pipeline_results" not in st.session_state:
    st.session_state.pipeline_results = None
if "last_run_metadata" not in st.session_state:
    st.session_state.last_run_metadata = None
if "map_city_selection" not in st.session_state:
    st.session_state.map_city_selection = "All Cities"

st.markdown(
    """
<style>
.opportunity-card {
    border: 1px solid rgba(255,255,255,0.12);
    border-radius: 16px;
    padding: 18px;
    margin-bottom: 16px;
    background: rgba(255,255,255,0.02);
    transition: transform 0.18s ease, box-shadow 0.18s ease;
}
.opportunity-card:hover {
    transform: translateY(-3px);
    box-shadow: 0 12px 28px rgba(0,0,0,0.35);
}
</style>
""",
    unsafe_allow_html=True,
)

st.title("AI Lead Generation Agents")
st.caption(
    "Discover local businesses, analyze websites, score opportunities, and generate outreach."
)

with st.sidebar:
    st.header("Search Settings")
    niches_input = st.text_area(
        "Niches (one per line)",
        value="dentists",
        height=100,
    )
    cities_input = st.text_area(
        "Cities (one per line)",
        value="miami",
        height=100,
    )
    max_results = st.number_input("Max Leads", min_value=1, max_value=100, value=5)
    outreach_limit = st.number_input("Outreach Limit", min_value=1, max_value=100, value=5)
    min_score = st.slider("Minimum Score", min_value=1, max_value=10, value=5)
    export_mode = st.selectbox(
        "Export Mode", ["Outreach Ready", "Lead List Only", "CRM Upload"]
    )
    run_clicked = st.button("Run Full Pipeline", use_container_width=True)

if run_clicked:
    try:
        niches, cities, search_pairs = parse_sidebar_inputs(niches_input, cities_input)

        progress_bar = st.progress(0)
        status_text = st.empty()

        pipeline_results = execute_full_pipeline(
            niches=niches,
            cities=cities,
            max_results=int(max_results),
            outreach_limit=int(outreach_limit),
            min_score=int(min_score),
            progress_bar=progress_bar,
            status_text=status_text,
        )

        st.session_state.pipeline_results = pipeline_results
        st.session_state.last_run_metadata = {
            "completed_at": datetime.now().isoformat(),
            "search_pairs_count": len(search_pairs),
            "niches_count": len(niches),
            "cities_count": len(cities),
        }

        status_text.empty()
    
    except Exception as e:
        st.error(f"Pipeline failed: {e}")

if st.session_state.pipeline_results is not None:
    render_full_results(st.session_state.pipeline_results, export_mode=export_mode)
